/**
 * Pre-run E1 judge-volume estimate (ADR-021 SO5-08). Hand-computed fixtures: the correct-reference fixture (10 file
 * units, 4 module units, as the SEN-01 live run recorded), a synthetic tree for each SEL-01 exclusion and the cap,
 * and the E1 arithmetic. No judge call.
 */
import { join } from 'node:path';
import {
  E1_CELLS, candidatesOf, e7BaseVolume, estimateE1, judgeHours, main, projectVolume, readTree, renderReport, specLayers, windowsNeeded,
} from '../../../../scripts/e1-judge-volume.js';
import type { TreeFile } from '../../../../scripts/e1-judge-volume.js';
import { readFileSync } from 'node:fs';
import { ROOT } from './score-fixture.js';

const LAYERS = specLayers(readFileSync(join(ROOT, 'specs/clean-arch.yaml'), 'utf8'));

describe('unit counting (BR-U4-SEL-01..04)', () => {
  it('clean-arch.yaml has the three layers', () => {
    expect(LAYERS.map((l) => [l.name, l.directories])).toEqual([['domain', ['src/domain/**']], ['application', ['src/application/**']], ['infrastructure', ['src/infrastructure/**']]]);
  });

  it('correct-reference: 10 files → 10 file units, 4 modules (SEN-01 recorded 10 and 4), 1 + 3 × 14 = 43 calls', () => {
    const v = projectVolume('fixture', readTree(join(ROOT, 'fixtures/correct-reference')), LAYERS);
    expect(v).toEqual({ label: 'fixture', tsFiles: 10, candidates: 10, fileUnits: 10, fileSelected: 10, moduleUnits: 4, moduleSelected: 4, calls: 43 });
  });

  it('each SEL-01 exclusion is counted once; only clean layered files remain', () => {
    const files: TreeFile[] = [
      { path: 'src/domain/a.ts', text: 'export class A {}\n' },
      { path: 'src/domain/index.ts', text: "export * from './a';\n" },
      { path: 'src/domain/__tests__/a.ts', text: 'export const t = 1;\n' },
      { path: 'src/application/x.e2e-spec.ts', text: 'export const e = 1;\n' },
      { path: 'src/infrastructure/generated/client.ts', text: 'export const g = 1;\n' },
      { path: 'src/infrastructure/db.ts', text: '// @generated by a tool\nexport const d = 1;\n' },
      { path: 'src/main.ts', text: 'export const m = 1;\n' },
    ];
    const c = candidatesOf(files, LAYERS);
    expect(c.files.map((f) => f.path)).toEqual(['src/domain/a.ts']);
    expect(c.exclusions).toEqual({ unlayered: 1, 'exclude-paths': 0, barrel: 1, 'test-path': 1, 'e2e-spec': 1, 'generated-path': 1, 'generated-marker': 1 });
    expect(c.uncoveredFiles).toEqual(['src/main.ts']);
  });

  it('25 domain files in 25 directories → 25 file units judged 20; modules coalesce to src/domain → 1; 1 + 3 × 21 = 64', () => {
    const files: TreeFile[] = Array.from({ length: 25 }, (_, i) => ({ path: `src/domain/d${String(i).padStart(2, '0')}/f.ts`, text: `export const v = ${String(i)};\n` }));
    const v = projectVolume('p', files, LAYERS);
    expect([v.fileUnits, v.fileSelected, v.moduleUnits, v.moduleSelected, v.calls]).toEqual([25, 20, 1, 1, 64]);
  });
});

describe('E1 arithmetic', () => {
  it('pilots 49 / 100 / 97 calls → low 2646, central ceil(54 × 82) = 4428, high 5400, ceiling 54 × 121 = 6534', () => {
    expect(estimateE1([49, 100, 97])).toEqual({ low: 2646, central: 4428, high: 5400, ceiling: 6534 });
    expect(E1_CELLS).toBe(54);
    expect(() => estimateE1([])).toThrow('no evidence project');
  });

  it('4428 calls × 6.57 s = 8.08 h sequential, 2.69 h at concurrency 3; 45 windows of 100 calls', () => {
    expect(judgeHours(4428)).toBeCloseTo(8.0811, 4);
    expect(judgeHours(4428, 6570, 3)).toBeCloseTo(2.6937, 4);
    expect(windowsNeeded(4428, 100)).toBe(45);
    expect(windowsNeeded(400, 100)).toBe(4);
  });

  it('the report states the central figure, the 6.6 s median and the cross-check verdict', () => {
    const p = { label: 'pilot-a', source: 'x', tsFiles: 1, candidates: 1, fileUnits: 1, fileSelected: 1, moduleUnits: 1, moduleSelected: 1, calls: 7 };
    const text = renderReport({ date: '2026-10-08', specPath: 's.yaml', projects: [p, { ...p, label: 'fixture', calls: 43, fileUnits: 10, moduleUnits: 4 }], crossChecks: [{ label: 'fixture', fileUnits: 10, moduleUnits: 4 }] });
    expect(text).toContain('| Central (pilot mean × 54) | 378 |');
    expect(text).toContain('6570 ms (6.6 s');
    expect(text).toContain('counted 10 and 4: **equal**');
  });
});

describe('CLI', () => {
  it('--self-test fails on a missing project directory; no pilot project is a usage error', () => {
    const err: string[] = [];
    const io = { out: () => undefined, err: (t: string) => err.push(t), writeFile: () => undefined };
    expect(main(['--self-test'], ROOT, io)).toBe(1);
    expect(err.join('')).toContain('is not a directory');
    expect(main(['--spec', 'specs/clean-arch.yaml', '--project', 'fixture=fixtures/correct-reference'], ROOT, io)).toBe(2);
  });

  it('writes the report for the fixture as its only pilot', () => {
    const written: string[] = [];
    const io = { out: () => undefined, err: () => undefined, writeFile: (_f: string, t: string) => written.push(t) };
    expect(main(['--spec', 'specs/clean-arch.yaml', '--project', 'pilot-ref=fixtures/correct-reference', '--date', '2026-10-08', '--out', 'x.md'], ROOT, io)).toBe(0);
    expect(written[0]).toContain(`| Central (pilot mean × 54) | ${String(43 * 54)} |`);
    expect(written[0]).not.toContain('--out');
  });
});

describe('--e7 mode (runbook stage 0c)', () => {
  const sel = (n01: number, n02: number): Parameters<typeof e7BaseVolume>[2] => ({
    projectId: 'p',
    functions: [
      { functionId: 'FF-N01', candidateUnitIds: Array.from({ length: n01 + 3 }, (_, i) => `m${String(i)}`), selectedUnitIds: Array.from({ length: n01 }, (_, i) => `m${String(i)}`) },
      { functionId: 'FF-N02', candidateUnitIds: Array.from({ length: n02 }, (_, i) => `f${String(i)}`), selectedUnitIds: Array.from({ length: n02 }, (_, i) => `f${String(i)}`) },
    ],
  });

  it('calls = 1 init probe + 3 × (selected FF-N01 + selected FF-N02); selected is capped at 20; a wrong id or missing function is undefined', () => {
    expect(e7BaseVolume('p', 's.yaml', sel(5, 19))?.calls).toBe(1 + 3 * 24);
    expect(e7BaseVolume('p', 's.yaml', sel(25, 20))).toMatchObject({ n01: { candidates: 28, selected: 20 }, calls: 1 + 3 * 40 });
    expect(e7BaseVolume('q', 's.yaml', sel(1, 1))).toBeUndefined();
    expect(e7BaseVolume('p', 's.yaml', { projectId: 'p', functions: [] })).toBeUndefined();
  });

  it('the registered e7-corpus plan with corpus/selections: 9 bases (ADR-027), sum and ceiling rows; a symbolic-only plan and a missing selection are refused', () => {
    const written: string[] = [];
    const err: string[] = [];
    const io = { out: () => undefined, err: (t: string) => err.push(t), writeFile: (_f: string, t: string) => written.push(t) };
    expect(main(['--e7', '--plan', 'experiments/e7-corpus/plan.json', '--selections', 'corpus/selections', '--date', '2026-10-09', '--out', 'x.md'], ROOT, io)).toBe(0);
    expect(written[0]).toContain('| Cap ceiling (9 × (1 + 3 × 2 × 20)) | 1089 |');
    expect(written[0]?.match(/^\| [a-zA-Z_-]+ \| `corpus\/specs\//gm)).toHaveLength(9);
    expect(main(['--e7', '--plan', 'experiments/latency-gate/plan.json', '--selections', 'corpus/selections'], ROOT, io)).toBe(1);
    expect(err.at(-1)).toContain('is not full mode');
    expect(main(['--e7', '--plan', 'experiments/e7-corpus/plan.json', '--selections', 'tests'], ROOT, io)).toBe(1);
    expect(err.at(-1)).toContain('not estimable');
    expect(main(['--e7', '--plan', 'experiments/e7-corpus/plan.json'], ROOT, io)).toBe(2);
  });
});
